# Generated by Django 2.0.3 on 2018-03-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.IntegerField()),
                ('sys_name', models.CharField(max_length=500)),
                ('create_time', models.DateField()),
                ('update_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startover_no', models.CharField(max_length=500)),
                ('pro_name', models.CharField(max_length=500)),
                ('sys_name', models.CharField(max_length=500)),
                ('thr_sys_test', models.FloatField()),
                ('thr_check_test', models.FloatField()),
                ('thr_mock_test', models.FloatField()),
            ],
        ),
    ]
