# Generated by Django 2.0.3 on 2018-03-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='assignVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.IntegerField(default=0)),
                ('publishplan_id', models.IntegerField(verbose_name=10)),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='publishPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sys_id', models.IntegerField(default=0)),
                ('sys_name', models.CharField(max_length=500)),
                ('stage', models.CharField(max_length=10)),
                ('plan_start_date', models.DateField()),
                ('actual_start_date', models.DateField(null=True)),
                ('plan_end_date', models.DateField()),
                ('actual_end_date', models.DateField(null=True)),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.IntegerField(default=0)),
                ('sys_name', models.CharField(max_length=500)),
                ('sys_id', models.IntegerField(default=0)),
                ('create_time', models.DateField()),
                ('update_time', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startover_no', models.CharField(max_length=500)),
                ('pro_name', models.CharField(max_length=500)),
                ('sys_name', models.CharField(max_length=500)),
                ('sys_id', models.IntegerField(default=10)),
                ('thr_sys_test', models.FloatField()),
                ('thr_check_test', models.FloatField()),
                ('thr_mock_test', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.IntegerField(verbose_name=10)),
                ('publishplan_id', models.IntegerField(default=0)),
                ('create_time', models.DateField()),
                ('update_time', models.DateField()),
            ],
        ),
    ]
