# Generated by Django 2.0.3 on 2018-04-02 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='publishplan_id',
            new_name='publish_plan_id',
        ),
    ]
