# Generated by Django 2.0.3 on 2018-04-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageplan',
            name='actual_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='actual_start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='plan_end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='plan_start_date',
            field=models.DateField(),
        ),
    ]
