# Generated by Django 2.0.3 on 2018-04-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20180420_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageplan',
            name='actual_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stageplan',
            name='actual_start_date',
            field=models.DateField(null=True),
        ),
    ]
