# Generated by Django 2.0.3 on 2018-04-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20180420_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versionplan',
            name='used_workload',
            field=models.FloatField(null=True),
        ),
    ]
