# Generated by Django 2.0.3 on 2018-04-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0004_auto_20180423_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageplan',
            name='used_workload',
            field=models.FloatField(null=True),
        ),
    ]
