# Generated by Django 2.0.3 on 2018-05-29 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0005_auto_20180423_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='redmine_users',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('login', models.CharField(blank=True, max_length=100, null=True)),
                ('HASHED_PASSWORD', models.CharField(blank=True, max_length=100, null=100)),
                ('FIRSTNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('LASTNAME', models.CharField(blank=True, max_length=100, null=True)),
                ('MAIL', models.CharField(blank=True, max_length=100, null=True)),
                ('ADMIN', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('LAST_LOGIN_ON', models.DateTimeField(blank=True, null=True)),
                ('LANGUAGE', models.CharField(blank=True, max_length=100, null=True)),
                ('AUTH_SOURCE_ID', models.CharField(blank=True, max_length=100, null=True)),
                ('CREATED_ON', models.DateTimeField(blank=True, null=True)),
                ('UPDATED_ON', models.DateTimeField(blank=True, null=True)),
                ('TYPE', models.CharField(blank=True, max_length=100, null=True)),
                ('IDENTITY_URL', models.CharField(blank=True, max_length=100, null=True)),
                ('MAIL_NOTIFICATION', models.CharField(blank=True, max_length=100, null=True)),
                ('SALT', models.CharField(blank=True, max_length=255, null=True)),
                ('MUST_CHANGE_PASSWD', models.CharField(blank=True, max_length=100, null=True)),
                ('PASSWD_CHANGED_ON', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'redmine_users',
            },
        ),
        migrations.CreateModel(
            name='StaffGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('contains_staffs', models.ManyToManyField(related_name='staff_group', to='TestModel.Staff')),
            ],
        ),
        migrations.CreateModel(
            name='SysGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
