# Generated by Django 2.0.3 on 2018-05-29 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0006_groupauth_redmine_users_staffgroup_sysgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Redmine_projects',
            fields=[
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('homepage', models.TextField(blank=True, null=True)),
                ('is_public', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(blank=True, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('identifier', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('lft', models.IntegerField(blank=True, null=True)),
                ('rgt', models.IntegerField(blank=True, null=True)),
                ('inherit_members', models.IntegerField(blank=True, null=True)),
                ('project_meeting_rooms', models.IntegerField(blank=True, null=True)),
                ('project_name_view', models.IntegerField(blank=True, null=True)),
                ('sys_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_starttime', models.DateTimeField(blank=True, null=True)),
                ('plan_endtime', models.DateTimeField(blank=True, null=True)),
                ('starttime', models.DateTimeField(blank=True, null=True)),
                ('endtime', models.DateTimeField(blank=True, null=True)),
                ('othersys', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Redmine_projects',
            },
        ),
        migrations.RenameField(
            model_name='staffgroup',
            old_name='operator',
            new_name='group_owner',
        ),
        migrations.AddField(
            model_name='versionplan',
            name='redmine_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='redmine_project_version_plan', to='TestModel.Redmine_projects'),
        ),
    ]
