# Generated by Django 2.0.3 on 2018-05-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0007_auto_20180529_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stageplan',
            name='plan_workload',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='versionplan',
            name='plan_workload',
            field=models.FloatField(null=True),
        ),
    ]
