# Generated by Django 2.0.3 on 2018-05-30 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0008_auto_20180529_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SysGroup',
        ),
        migrations.AddField(
            model_name='assignactionrecord',
            name='disable_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='contains_system',
            field=models.ManyToManyField(related_name='version_group', to='TestModel.VersionPlan'),
        ),
        migrations.AddField(
            model_name='staffgroup',
            name='group_name',
            field=models.CharField(default='default_group', max_length=100),
        ),
        migrations.AlterField(
            model_name='staffgroup',
            name='group_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
