# staff_type
AUTH_TYPE_MANAGER = 0
AUTH_TYPE_USER = 1
AUTH_TYP_DEVELOPER = 2
# assigned
AUTH_STATUS_ASSIGNED = 0
AUTH_STATUS_UNASSIGNED = 1
# use_activity
AUTH_USER_ACTIVITY = True
AUth_USER_DISABLE = False


