# staff_type
AUTH_TYPE_MANAGER = 0
AUTH_TYPE_USER = 1
AUTH_TYP_DEVELOPER = 2
# assigned
AUTH_STATUS_ASSIGNED = 0
AUTH_STATUS_UNASSIGNED = 1
# use_activity
AUTH_USER_ACTIVITY = True
AUTH_USER_DISABLE = False
#group_auth_type
AUTH_GROUP_USER = 1
AUTH_GROUP_ADMIN = 2
AUTH_GROUP_APPLY = 3
AUTH_GROUP_REFUSE = 4


